refactor job

diff --git a/.github/workflows/integrational-tests.yml b/.github/workflows/integrational-tests.yml
--- a/.github/workflows/integrational-tests.yml
+++ b/.github/workflows/integrational-tests.yml
@@ -35,6 +35,12 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
+
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+
     # Setup gcloud CLI
     - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
       with:
@@ -50,20 +56,24 @@ jobs:
 
     - run: |-
         kubectl config use-context $(kubectl config get-contexts -o name)
+      continue-on-error: true
 
     - name: Apply RBAC
       run: |-
         kubectl apply -f rbac.yaml
+      continue-on-error: true
 
     - name: Deploy Hazelcast cluster
       run: |-
         kubectl apply -f hazelcast-cluster.yaml
+      continue-on-error: true
 
     - name: Wait for deployment to finish
       run: |-
         kubectl wait --for=condition=ready pod/hazelcast-0 --timeout=20s
         kubectl wait --for=condition=ready pod/hazelcast-1 --timeout=20s
         kubectl wait --for=condition=ready pod/hazelcast-2 --timeout=20s
+      continue-on-error: true
 
     - name: Creating LoadBalancer for each pods
       run: |-
@@ -71,12 +81,14 @@ jobs:
           kubectl create service loadbalancer ${pod} --tcp=5701 -o yaml --dry-run | kubectl set selector --local -f - "statefulset.kubernetes.io/pod-name=${pod}" -o yaml | kubectl create -f -; \
           kubectl label service ${pod} test=true; \
         done;
+      continue-on-error: true
 
     - name: Fetch k8s master IP
       id: master-ip
       run: |-
         ip=$(kubectl cluster-info | grep master | awk -Fat '{gsub(/ /, "", $0); print $NF}')
-        echo "::set-output name=ip::$ip"
+        echo "masterIp=$ip" >> $GITHUB_ENV
+      continue-on-error: true
 
     - name: Fetch k8s escrets
       id: secrets
@@ -87,85 +99,23 @@ jobs:
         caCertificate="${caCertificate//'%'/'%25'}"
         caCertificate="${caCertificate//$'\n'/'%0A'}"
         caCertificate="${caCertificate//$'\r'/'%0D'}"
-        echo "::set-output name=apiToken::$apiToken"
-        echo "::set-output name=caCertificate::$caCertificate"
-
-  run-maven:
-    name: Run Maven tests
-    runs-on: ubuntu-latest
-    needs: run-tests
-    continue-on-error: true
-
-    outputs:
-      test-failed: ${{ steps.test.outputs.testFailed }}
-
-    steps:
-
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Set up JDK 1.8
-      uses: actions/setup-java@v1
-      with:
-        java-version: 1.8
+        echo "apiToken=$apiToken" >> $GITHUB_ENV
+        echo "caCertificate=$caCertificate" >> $GITHUB_ENV
+      continue-on-error: true
 
     - name: Run Maven tests
       run: |-
-        caCertificate="${{ needs.run-tests.outputs.ca_certificate }}"
-        apiToken="${{ needs.run-tests.outputs.api_token }}"
-        masterIp="${{ needs.run-tests.outputs.master_ip }}"
         KUBERNETES_MASTER="$masterIp" API_TOKEN=$apiToken CA_CERTIFICATE=$caCertificate mvn test -q
       continue-on-error: true
 
-    - name: The job has failed
-      id: test
-      if: ${{ failure() }}
-      run: |-
-        echo "::set-output name=testFailed::true"
-
-  cleanup:
-    name: Clean up
-    runs-on: ubuntu-latest
-
-    # wait until run-maven finishes but run the cleanup even if it fails
-    needs: run-maven
-    if: true
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
-      with:
-        service_account_key: ${{ secrets.GKE_SA_KEY }}
-        project_id: ${{ env.PROJECT_ID }}
-        export_default_credentials: true
-
-    - run: |-
-        gcloud components install kubectl
-
-    - run: |-
-        gcloud container clusters get-credentials --region="$GKE_ZONE" "$GKE_CLUSTER"
-
-    - run: |-
-        kubectl config use-context $(kubectl config get-contexts -o name)
-
-    - name: Clean up service
+    # Clean up
+    - name: Clean up resources
       run: |-
         kubectl delete svc --selector='test=true'
-      continue-on-error: true
-
-    - name: Clean up RBAC
-      run: |-
         kubectl delete -f rbac.yaml --ignore-not-found=true
-      continue-on-error: true
-
-    - name: Clean up StatefulSet
-      run: |-
         kubectl delete -f hazelcast-cluster.yaml --ignore-not-found=true
       continue-on-error: true
 
-    - name: Test result
-      run: |-
-        testResult="${{ needs.run-tests.outputs.test-failed }}"
-        exit 1
+    - name: Job has failed
+      if: ${{ failure() }}
+      run: exit 1
